services:
  go_api:
    container_name: go_api
    image: go-api-products
    build: .
    ports:
      - "8000:8000"
    depends_on:
      go_db:
        condition: service_healthy

  go_db:
    container_name: go_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: